In [112]:
w1, w2 = [l.strip() for l in open('input') if l.strip()]

In [116]:
w2.split(',')

['L1003',
 'D878',
 'R937',
 'D979',
 'R921',
 'U572',
 'R4',
 'D959',
 'L884',
 'U394',
 'R221',
 'U206',
 'R806',
 'U912',
 'R345',
 'D290',
 'R65',
 'D996',
 'L411',
 'D157',
 'R590',
 'D557',
 'L32',
 'D360',
 'L691',
 'D861',
 'L156',
 'D603',
 'R733',
 'U444',
 'L433',
 'U144',
 'L238',
 'U213',
 'R827',
 'U949',
 'R384',
 'D409',
 'L727',
 'U923',
 'L98',
 'U781',
 'L201',
 'D200',
 'R749',
 'U288',
 'L486',
 'U158',
 'L494',
 'D522',
 'R636',
 'D330',
 'L507',
 'U691',
 'R918',
 'D706',
 'R163',
 'U609',
 'R559',
 'U674',
 'R784',
 'D87',
 'R670',
 'U401',
 'L85',
 'U981',
 'R848',
 'D579',
 'L882',
 'U777',
 'R671',
 'D385',
 'R913',
 'D899',
 'R92',
 'D780',
 'L795',
 'U821',
 'R956',
 'U446',
 'L109',
 'D955',
 'L570',
 'D874',
 'R499',
 'U845',
 'R769',
 'U88',
 'L529',
 'U657',
 'R553',
 'D357',
 'L83',
 'D324',
 'L273',
 'U689',
 'L715',
 'U933',
 'R161',
 'U561',
 'L603',
 'U349',
 'L445',
 'U781',
 'R299',
 'U26',
 'L212',
 'U429',
 'R763',
 'U116',
 'R961',
 'D258',
 '

In [21]:
def follow(coords):
    pos = []
    x = 0
    y = 0
    for change in coords.split(','):
        pos.append((x, y))
        dir, *dist = change
        dist = int(''.join(dist))
        if dir == 'R':
            y += dist
        elif dir == 'U':
            x -= dist
        elif dir == 'L':
            y -= dist
        elif dir == 'D':
            x += dist
        else:
            raise RuntimeException()
    return min(p[0] for p in pos), max(p[0] for p in pos), min(p[1] for p in pos), max(p[1] for p in pos)

In [23]:
print(follow(w1), follow(w2))

(-7720, 0, -1834, 9284) (-6128, 4556, -4662, 6332)


In [25]:
import numpy as np

In [178]:
def follow2(coords, grid):
    x = 10_000
    y = 10_000
    total_dist = 0
    for change in coords.split(','):
        dir = change[0]
        dist = int(change[1:])
        if dir == 'R':
            grid[x, y+1:y+dist+1] += np.asarray(range(1, dist+1)) + total_dist
            y += dist
        elif dir == 'U':
            grid[x-dist:x, y] += np.asarray(range(dist, 0, -1)) + total_dist
            x -= dist
        elif dir == 'L':
            grid[x, y-dist:y] += np.asarray(range(dist, 0, -1)) + total_dist
            y -= dist
        elif dir == 'D':
            grid[x+1:x+dist+1, y] += np.asarray(range(1, dist+1)) + total_dist
            x += dist
        else:
            raise RuntimeException()
        total_dist += dist

In [179]:
grid1 = np.zeros((20_000, 20_000))
grid2 = np.zeros((20_000, 20_000))

In [180]:
follow2(w1, grid1)

In [181]:
follow2(w2, grid2)

In [182]:
candidates = np.argwhere(np.logical_and(grid1 > 0, grid2 > 0))
len(candidates)

24

In [183]:
def dist(pt):
    return grid1[pt[0], pt[1]] + grid2[pt[0], pt[1]]

In [184]:
candidates_pos = [(c, dist(c)) for c in candidates]

In [185]:
sorted(candidates_pos, key=lambda x: x[1])

[(array([ 7528, 14399]), 101386.0),
 (array([ 7552, 14399]), 101792.0),
 (array([ 7564, 14344]), 102396.0),
 (array([ 7564, 14350]), 102942.0),
 (array([8582, 8166]), 121816.0),
 (array([8918, 8416]), 121816.0),
 (array([9841, 8867]), 130328.0),
 (array([9905, 8884]), 130328.0),
 (array([ 7358, 14411]), 182360.0),
 (array([ 7189, 15343]), 185726.0),
 (array([ 7546, 14850]), 188118.0),
 (array([ 7528, 14685]), 188484.0),
 (array([ 7358, 14344]), 188742.0),
 (array([ 7358, 14350]), 188876.0),
 (array([ 7933, 15617]), 200012.0),
 (array([ 7189, 15812]), 200580.0),
 (array([ 7447, 15812]), 201226.0),
 (array([ 7877, 15617]), 201226.0),
 (array([ 7189, 15937]), 202584.0),
 (array([ 7438, 16135]), 202584.0),
 (array([ 7741, 15294]), 205802.0),
 (array([ 7877, 15294]), 206098.0),
 (array([ 7741, 15501]), 206274.0),
 (array([ 7854, 15146]), 207210.0)]